# Generated by Django 4.2.11 on 2024-05-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('m2_construidos', models.DecimalField(decimal_places=2, max_digits=6)),
                ('m2_totales', models.DecimalField(decimal_places=2, max_digits=6)),
                ('estacionamientos', models.PositiveIntegerField()),
                ('habitaciones', models.PositiveIntegerField()),
                ('banos', models.PositiveIntegerField()),
                ('direccion', models.CharField(max_length=255)),
                ('comuna', models.CharField(max_length=50)),
                ('tipo_inmueble', models.CharField(max_length=20)),
                ('precio_arriendo', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=254)),
                ('tipo_usuario', models.CharField(max_length=20)),
            ],
        ),
    ]
